version: 2

sources:
  - name: raw_yellow_tripdata
    description: "Raw NYC Yellow Taxi trip data loaded from Snowflake"
    database: NYC_TAXI_DB   
    schema: RAW
    tables:
      - name: YELLOW_TRIPDATA