name: NYC Taxi ETL & dbt

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 5 * *'

jobs:
  etl_dbt:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Run Python ETL
      #   env:
      #     SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      #     SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      #     SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      #     DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
      #   run: python init_snowflake.py
      
      - name: Setup dbt profiles
        run: |
          mkdir -p ~/.dbt
          echo "
          nyc_taxi_dbt:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: $SNOWFLAKE_ACCOUNT
                user: $SNOWFLAKE_USER
                password: $DBT_PASSWORD
                role: TRANSFORM
                database: NYC_TAXI_DB
                warehouse: NYC_TAXI_WH
                schema: RAW
                threads: 1
                client_session_keep_alive: False
          " > ~/.dbt/profiles.yml
        shell: bash

      - name: Run dbt Build
        env:
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        run: |
          export DBT_USER=$SNOWFLAKE_USER
          export DBT_PASSWORD=$DBT_PASSWORD
          export DBT_ACCOUNT=$SNOWFLAKE_ACCOUNT
          dbt build --project-dir nyc_taxi_dbt