name: NYC Taxi ETL & dbt

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'  # tous les jours à 2h UTC

jobs:
  etl_dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dbt-snowflake apache-airflow apache-airflow-providers-snowflake

      - name: Run Python ETL
        run: python init_snowflake.py

      - name: Run dbt Build
        run: dbt build --project-dir nyc_taxi_dbt